var Config = {
    "port": 3030,
    "debug": true,
    "monitor": false,
    "itemsConfig": [{
        "itemsName": "",
        "localPath": "",
        "destPath": "",
        "releasePath": "",
        "testPath": "",
        "ftpHost": "",
        "ftpPort": "",
        "ftpRemotePath": "",
        "ftpUser": "",
        "ftpPassword": "",
        "spriteName": "",
        "spriteNameSwitch": true,
        "cssNameSwitch": false,
        "cssName": "201612052004",
        "ftpSwitch": false,
        "imgMasterSwitch": true,
        "resourceSyncSwitch": false,
        "pxToRemSwitch": false,
        "timeStampSwitch": true,
        "rootValue": "75",
        "svnSwitch": false,
        "propertyBlackList": "",
        "svnReleasePath": "",
        "destPathSwitch": true,
        "versionsSyncSwitch": false,
        "versionsFilePath": "",
        "spriteFolderSwitch": false,
        "spriteFolderName": "slice",
        "svnLocalPath": "",
        "svnUser": "",
        "svnPassword": "",
        "httpRemote": "",
        "httpTestPath": "",
        "httpReleasePath": "",
        "httpSwitch": true,
        "ftpType": "ftp",
        "jsMinSwitch": false,
        "httpToken": ""
    }]
}
module.exports = Config;